site_name: Wiki

theme:
  name: "material"
  font: false
  features:
    - instant
    - navigation.expand
    - tabs

extra_css:
  - _styles/extra.css

plugins:
  - search

repo_url: https://github.com/4eUeP/open-notes
repo_name: 4eUeP/open-notes

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
